### PR TITLE
French translation added

### PR DESCRIPTION
**Pull request by Lactic68**

### CODE REVIEW

**Comment by tn4799** [comment]
Thanks for your work. 
With the new version 1.2.0.0 we added a coulple of new features. Could you add them too in your translations

**Comment by Lactic68** [comment]
Hi @tn4799 ,
FR translations for 1.2.0.0 added ;)

**Comment by tn4799** [comment]
Thanks

**Comment by Tensuko** [comment]
Hi! Thanks for the translation :)

**Pull request merged**
